CREATE DATABASE IF NOT EXISTS LMS;
USE LMS;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    usertype ENUM('ADMIN','USER') NOT NULL,
    passw VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan (
    loan_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,

    principal DOUBLE NOT NULL,
    months INT NOT NULL,
    interest_rate DOUBLE NOT NULL,

    remaining DOUBLE NOT NULL,
    status ENUM('PENDING','APPROVED','REJECTED','CLOSED','DEFAULTED') NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP NULL,
    closed_at TIMESTAMP NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);